#!/bin/sh

nr_threads=`getconf NPROCESSORS_CONF`

set -e
set -x

netbsd_root=/public
MAKE_FLAGS='DESTDIR='"$netbsd_root/destdir/"' USETOOLS=no MKLLVM=yes HAVE_LLVM=yes MKGCC=no'
SANITIZERS=none

count=0
target=
for i in $@; do
    count=$(($count + 1))
    target=$target" "$i
done

if [ "$SANITIZERS" = "none" ]; then
    SANFLAGS=""
else
    SANFLAGS='-fsanitize='"$SANITIZERS"''
fi
LLVM_BIN=/public/afl-2.52b
COMPILE_FLAGS='"$SANFLAGS" -g -O0'
LINK_FLAGS='"$SANFLAGS" -g -O0'
CCFLAGS='CC='"$LLVM_BIN"'/afl-clang CFLAGS="'"$COMPILE_FLAGS"'" CXX='"$LLVM_BIN"'/afl-clang++ CXXFLAGS="'"$COMPILE_FLAGS"'"'
LDFLAGS='LDFLAGS="'"$LINK_FLAGS"'"'
LIB_LDFLAGS='LDFLAGS="'"$COMPILE_FLAGS"'"'

if [ "$no_link" = "true" ]; then
    ALL_FLAGS="$MAKE_FLAGS $CCFLAGS $LIB_LDFLAGS"
else
    ALL_FLAGS="$MAKE_FLAGS $CCFLAGS $LDFLAGS"
fi

build="make $ALL_FLAGS $target"
eval $build
